name: Build and push images to Dockerhub

on:
  push:
    branches:
      - master
      
jobs:
  build-and-push-client:
    name: Build and Push Client
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: epiii/thingsyouforget-client
        dockerfile: client/Dockerfile
        tags: latest
  
  build-and-push-admin:
    name: Build and Push Admin
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: epiii/thingsyouforget-admin
        dockerfile: admin/Dockerfile
        tags: latest
 
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: epiii/thingsyouforget-backend
        dockerfile: backend/Dockerfile
        tags: latest
      
  build-and-push-nginx:
    name: Build and Push Nginx
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: epiii/thingsyouforget-nginx
        dockerfile: nginx/Dockerfile
        tags: latest
