name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push Client
        uses: docker/build-push-action@v2.8.0
        with:
          context: client
          push: true
          tags: epiii/thingsyouforget-client:latest
      -
        name: Build and push Nginx
        uses: docker/build-push-action@v2.8.0
        with:
          context: nginx
          push: true
          tags: epiii/thingsyouforget-nginx:latest
      -
        name: Build and push Admin
        uses: docker/build-push-action@v2.8.0
        with:
          context: admin
          push: true
          tags: epiii/thingsyouforget-admin:latest
      -
        name: Build and push Backend
        uses: docker/build-push-action@v2.8.0
        with:
          context: backend
          push: true
          tags: epiii/thingsyouforget-backend:latest
